Incremental Search for User Search
03san-smz/chat-space pull request #13
Opened 2019-02-27 08:45 UTC by 03san-smz

2019-02-27 08:49 UTC, 03san-smz commented
#WHAT  
インクリメンタルサーチの実装

#WHY  
新規グループにメンバー追加するのを非同期通信で行うため

2019-02-27 08:50 UTC, 03san-smz commented
ビューの動きの動画キャプチャを添付します。
https://gyazo.com/e1617811cc50d466777ce812cb82aae0

2019-02-27 08:53 UTC, yusukeyamane commented on app/assets/javascripts/user.js
> +  function appendNoUser(user){
appendNoUserとなってますが、Userを追加しているように見えるので、もう少し内容を反映した名前にしたいですね

2019-02-27 08:55 UTC, yusukeyamane commented on app/assets/javascripts/user.js
> +      $("#user-search-result").empty();
これemptyにする処理不要ではないですかね？inputがnilの場合の条件なので

2019-02-27 08:55 UTC, yusukeyamane commented on app/assets/javascripts/user.js
> +    console.log();
消しておきましょう

2019-02-27 08:55 UTC, yusukeyamane commented on app/controllers/messages_controller.rb
> +      format.json{ @new_message = @messages.where('id > ?', params[:id]) }
これ、何のための記述ですか？

2019-02-27 11:34 UTC, 03san-smz commented on app/controllers/messages_controller.rb
> +      format.json{ @new_message = @messages.where('id > ?', params[:id]) }
ローカルとリモートでファイルが違ったのでmacを再起動したら作業データが消えてしまいました。その場合リモートをダウンロードした方がいいのでしょうか？

2019-02-27 11:36 UTC, yuki-uchida commented
指摘に対しては、一つ一つリプライする形で対応を記述してください

2019-02-27 11:37 UTC, yuki-uchida requested changes

2019-02-27 11:37 UTC, yuki-uchida commented on app/assets/javascripts/user.js
> +      $("#user-search-result").empty();
こちら対応されましたか？

2019-02-27 11:37 UTC, yuki-uchida commented on app/assets/javascripts/user.js
> +    console.log();
こちらも

2019-02-27 11:37 UTC, yuki-uchida commented on app/controllers/messages_controller.rb
> +      format.json{ @new_message = @messages.where('id > ?', params[:id]) }
そうですね、その場合はリモートのデータをgit pullで持ってきてから再度開発に戻りましょう

2019-02-27 12:20 UTC, 03san-smz commented on app/assets/javascripts/user.js
> +  function appendNoUser(user){
命名を変更しました

2019-02-27 12:21 UTC, 03san-smz commented on app/assets/javascripts/user.js
> +    console.log();
削除しました！

2019-02-27 12:22 UTC, 03san-smz commented on app/controllers/messages_controller.rb
> +      format.json{ @new_message = @messages.where('id > ?', params[:id]) }
respond_toを削除しました。ローカルで作業していたファイルとリモートがうまく反映されてませんでした。

2019-02-27 12:33 UTC, 03san-smz commented on app/assets/javascripts/user.js
> +      $("#user-search-result").empty();
修正いたしました

2019-02-27 12:54 UTC, yuki-uchida requested changes

2019-02-27 12:54 UTC, yuki-uchida commented on app/assets/javascripts/user.js
> +  function addUser(name,user_id){
appendUserでは、何をどうするのかがわかりづらいので、appendSearchUserResultとかはいかがでしょうか

2019-02-27 12:54 UTC, yuki-uchida commented on app/assets/javascripts/user.js
> +    .done(function(data){
dataでは、何を受け取ったのかわからないので、それがわかる名前に変えましょう

2019-02-27 13:03 UTC, 03san-smz commented on app/assets/javascripts/user.js
> +  function addUser(name,user_id){
命名を修正しました。

2019-02-27 13:04 UTC, 03san-smz commented on app/assets/javascripts/user.js
> +    .done(function(data){
命名を修正しました。

2019-02-27 13:07 UTC, yuki-uchida requested changes

2019-02-27 13:07 UTC, yuki-uchida commented on app/assets/javascripts/user.js
> +  function addUser(name,user_id){
adduserもですね

2019-02-27 13:11 UTC, 03san-smz commented on app/assets/javascripts/user.js
> +  function addUser(name,user_id){
groupAddUserに命名を修正しました

2019-02-28 02:02 UTC, miyagit commented on app/views/groups/_form.html.haml
> +        - @group.users.each do |user|
部分テンプレートを使いましょう。

2019-02-28 02:12 UTC, 03san-smz commented on app/views/groups/_form.html.haml
> +        - @group.users.each do |user|
部分テンプレートに切り分けました！

2019-02-28 02:14 UTC, hzak2xx approved these changes
LGTM

2019-02-28 02:15 UTC, merged